#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Setup monitors
autorandr --cycle &

# Start compositing
picom --experimental-backends &

# Start lock screen automatically
xss-lock --transfer-sleep-lock -- i3lock -n -t -i $HOME/.scripts/lock-phoenix.png &
xset s 300 &
xset dpms 0 360 420 &

# Start clipmenu
systemctl --user restart clipmenud

# Start window manager
exec i3
