[theme]
background = "#0c0c0c"
primary = "#cccccc"
secondary = "#0037DA"
title = "#C19C00"
playing = "#13A10E"
playing_selected = "#13A10E"
playing_bg = "#1C1C1C"
highlight = "#F2F2F2"
highlight_bg = "#1C1C1C"
error = "#F2F2F2"
error_bg = "#c50f1f"
statusbar = "#F2F2F2"
statusbar_progress = "#C19C00"
statusbar_bg = "#1C1C1C"
cmdline = "#C19C00"
cmdline_bg = "#1C1C1C"
