sensors:
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon2
    indices: [1, 2, 3]
  - hwmon: /sys/devices/virtual/thermal/thermal_zone0/hwmon0
    indices: [1]

fans:
  - tpacpi: /proc/acpi/ibm/fan

#
# Simple level config
# meaning: [FANSPEED, LOWER_LIMIT, UPPER_LIMIT]
#
levels:
  - [0, 0,  40]
  - [1, 32, 55]
  - [2, 54, 66]
  - [3, 65, 76]
  - [4, 75, 80]
  - [5, 78, 85]
  - [6, 82, 88]
  - [7, 85, 32767]
