#!/bin/bash

screen_num="$(xrandr | grep -c -P "[e]?DP-[1,2] connected")"

if [[ $screen_num = 3 ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --pos 988x1200 --rotate normal --output DP-1 --mode 1920x1200 --pos 1920x0 --rotate normal --output DP-2 --mode 1920x1200 --pos 0x0 --rotate normal --output HDMI-1 --off
elif [[ $screen_num = 2 ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x1080 --rotate normal --output DP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --off --output HDMI-1 --off
else
    xrandr --output eDP-1 --primary --mode 1920x1080 --pos 988x1200 --rotate normal --output DP-1 --off --output DP-2 --off --output HDMI-1 --off
fi
